### ISSUE TITLE
Does not show the name

### ISSUE THREAD

**Issue by GENESIS-PLUS** [gradus0/appleAuth#2]
Everything is super, great job. But for some reason it does not show the name, but I would like it too.

**Comment by gradus0** [comment]
> Everything is super, great job. But for some reason it does not show the name, but I would like it too.

What's the name ?
If user name, then:
apple gives the name only on the first authorization request, hides the next ones.
Login into your apple id and remove access to the site.
https://appleid.apple.com/account/manage

And authorization again through the script

**Comment by GENESIS-PLUS** [comment]
Ok, thanks.

**Comment by sreenumalae** [comment]
I'm facing the same issue.

Sign in workflow goes well.

But even in the first authorization request, I can see only the EMAIL.
I don't see the name.

As you said I Logged in to my appleid (https://appleid.apple.com/account/manage)  and remove access to the site and run the script again.

But i can see only the email.

`array(5) { ["access_token"]=> string(63) "a80dfaf42dcac4bdba432d4bc3d1caa12.0.mzyz.2_BOSKh_f9fRbEcN6iVKKA" ["token_type"]=> string(6) "Bearer" ["expires_in"]=> int(3600) ["refresh_token"]=> string(63) "rb7ce943f96344f94b7ae71fb29519686.0.mzyz.m8vJ25ITk2L6JwVQlRxhGQ" ["id_token"]=> string(811) "eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmhsLmRlbW9zIiwiZXhwIjoxNjY1NTc4ODk3LCJpYXQiOjE2NjU0OTI0OTcsInN1YiI6IjAwMDk4OS45NDNkMjY4NDRiNjA0OWE5ODBjMjlhMGNhZjdlNjJjOS4wOTEzIiwiYXRfaGFzaCI6IlRNd2w1OGgzOGVyTWZWYm5oOHcxNWciLCJlbWFpbCI6Imc4bWtnMmh5N2pAcHJpdmF0ZXJlbGF5LmFwcGxlaWQuY29tIiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwiaXNfcHJpdmF0ZV9lbWFpbCI6InRydWUiLCJhdXRoX3RpbWUiOjE2NjU0OTI0OTUsIm5vbmNlX3N1cHBvcnRlZCI6dHJ1ZX0.N1qK2nOEdNeUk1RekjaMvqnPdSi7bU6hiLgts86Ke_Mou1q4uqlrWzJiIAbAguVJv9BBZ8CETS8qIy31xC_oPyzd-ohL1kVzL-KAElmYk0YqUDAx_wx6edlQ0bNPCndPJEXvRGSrPs6HJwzXgqYmlTyuX0KApBvQBGwav_mXD-UZ4U-PegCbBz3jR8rNzS5SV1Wlvg-B0OohQN40pHCwdGhIJziyPLwsEO9G_nwwh3PLd0gV_aA0kDJOcfrjnPVU0QdLo5zKFsdD1VORkn9rzpmb8ILW0jz4BhU1BY-G_U74z_axWK5slcxSZCJdtrgmzzkZhZwilH2Mr6QK9-hAVg" } array(3) { ["header"]=> object(stdClass)#2 (2) { ["kid"]=> string(6) "YuyXoY" ["alg"]=> string(5) "RS256" } ["payload"]=> array(11) { ["iss"]=> string(25) "https://appleid.apple.com" ["aud"]=> string(12) "com.hl.demos" ["exp"]=> int(1665578897) ["iat"]=> int(1665492497) ["sub"]=> string(44) "000989.943d26844b6049a980c29a0caf7e62c9.0913" ["at_hash"]=> string(22) "TMwl58h38erMfVbnh8w15g" ["email"]=> string(35) "g8mkg2hy7j@privaterelay.appleid.com" ["email_verified"]=> string(4) "true" ["is_private_email"]=> string(4) "true" ["auth_time"]=> int(1665492495) ["nonce_supported"]=> bool(true) } ["hash"]=> string(44) "gySDpCkyp516jWrgMiFDoYVfbDtaiHHb7uk9falxBpQ=" }`
